---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-dns-checker
  labels:
    app: kube-dns-checker
spec:
  selector:
    matchLabels:
      app: kube-dns-checker
  template:
    metadata:
      labels:
        app: kube-dns-checker
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
        prometheus.io/scheme: 'http'
    spec:
      containers:
        - name: kube-dns-checker
          image: radut/kube-dns-checker
          imagePullPolicy: Always
          env:
            - name: DOMAINS
              value: "www.google.com"
            - name: GO_RESOLVER
              value: "false"
            - name: NAMESERVERS
#              value: "DEFAULT,10.233.0.3"
              value: "DEFAULT"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /live
#              port: 8080
#            #              httpHeaders:
#            #                - name: X-Custom-Header
#            #                  value: Awesome
#            initialDelaySeconds: 10
#            periodSeconds: 3
#      priorityClassName: system-cluster-critical
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/disk-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/pid-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/unschedulable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/network-unavailable
          operator: Exists
