---
apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-dns-checker
  namespace: monitor
  labels:
    name: kube-dns-checker
spec:
  template:
    metadata:
      labels:
        name: kube-dns-checker
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
        prometheus.io/scheme: 'http'
    spec:
      containers:
        - name: kube-dns-checker
          image: radut/kube-dns-checker
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/disk-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
